### PR TITLE
Add DAS Trainer calibration

### PR DESCRIPTION
**Pull request by blakegong**
Works beautifully 😍 

Apr-19-2020 01-09-14

### CODE REVIEW

**Review by timotheeg — COMMENTED** [review]
Wow. That is very nice!! Thanks @blakegong!

I think Alex has a pattern in the calibrator to open optional tabs. For example the field tab is only seen when the field capturing is checkbox-activated in the options (instead of having a checkbox in the tab content itself).

We can change this later though, I'm super happy to have Das Trainer capturing in the calibrator!!

**Comment by blakegong** [comment]
Haha yeah I'd do it later. Enough tkinter GUI writing for a week 😂

**Comment by timotheeg** [comment]
Oh btw, Tristan was complaining to me the other day, that my das trainer capture is not as good as das trainer itself, because i do not capture the loss of das, and then display that in the UI. 

From his perspective just high das on piece start is not a good enough measure of skill, which I guess is fair enough.

I have an idea to represent that in NESTrisStatsUI, so at some point, in das trainer OCR, i might try to capture it, and I was thinking there are 2 ways:

1. Try to detect the icon next to the Start Das value to detect for the cross
2. OCR the current das value at every single frame (instead of just the start das), and record when the das value drops

Feature creep! 😄

**Comment by blakegong** [comment]
> OCR the current das value at every single frame (instead of just the start das), and record when the das value drops

Nooooo... Capture the "end DAS" from the list below instead. So you'd be capturing both "start DAS" and "end DAS". It's just one more 2-digit number that wouldn't require capturing frame-by-frame.

**Comment by timotheeg** [comment]
> Nooooo... Capture the "end DAS" from the list below instead. So you'd be capturing both "start DAS" and "end DAS". It's just one more 2-digit number that wouldn't require capturing frame-by-frame.

Ho that's a good idea! Thanks 😄

**Comment by timotheeg** [comment]
Wait a minute, are you sure the value below is the end das? I thought it was still the start das of the piece 🤔 with only the cross being an indicator of having lost das during that particular piece

**Comment by blakegong** [comment]
Ohhhh yeah.... Right 😓 So need OCR the hearts instead? 😂

**Pull request merged**
